---
- hosts: all
  vars:
    db_root_password: "password1234"
    db_password: "password1234"
  become: yes
  tasks:
    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Install MySQL
      apt:
        name: "{{ packages }}"
      vars:
        packages:
            - mysql-server-5.7
            - default-libmysqlclient-dev

    - name: Install Python MySQL Module
      pip:
        name: MySQL-Python
 
    - name: Set Root Password
      mysql_user: user=root password="{{ db_root_password }}" host=localhost

    - name: Remove anonymous users for localhost
      mysql_user: login_user="root" login_password="{{ db_root_password }}" user="" state="absent"

    - name: Securing root user for localhost
      mysql_user: login_user="root" login_password="{{ db_root_password }}" user="root" password="{{ db_root_password }}" host="127.0.0.1"

    - name: Securing root user for localhost domain
      mysql_user: login_user="root" login_password="{{ db_root_password }}" user="root" password="{{ db_root_password }}" host="localhost"   

    - name: Removing Test Database
      mysql_db: login_user=root login_password="{{ db_root_password }}" db=test state=absent

    - name: Change mysql config
      shell: sed -i "s/bind-address.*/bind-address = 0.0.0.0/g" /etc/mysql/mysql.conf.d/mysqld.cnf
      become: yes

    - name: Restart MySQL
      service:
        name: mysql
        state: restarted
      become: yes

    - name: Install LAMP and other dependencies
      apt:
        name: "{{ packages }}"
      vars:
        packages:
          - apache2
          - software-properties-common
          - libapache2-mod-php
          - curl
          - python3-pip
          - php7.2
      become: yes

    - name: Edit Apache Config file
      shell: sed -i 's/DirectoryIndex index\.html index\.cgi index\.pl index\.php index\.xhtml index\.htm/DirectoryIndex index\.php index\.html index\.cgi index\.pl index\.xhtml index\.htm/g' /etc/apache2/mods-enabled/dir.conf
      become: yes

    - name: Add ownCloud APT keys
      shell: curl https://download.owncloud.org/download/repositories/production/Ubuntu_18.04/Release.key | sudo apt-key add -
      become: yes

    - name: Add owncloud to sources.list
      shell: echo 'deb http://download.owncloud.org/download/repositories/production/Ubuntu_18.04/ /' | sudo tee /etc/apt/sources.list.d/owncloud.list
      become: yes

    - name: Update cache
      apt:
        update_cache: yes
      become: yes
      become_method: sudo

    - name: Install owncloud and php mods
      apt:
        name: "{{ packages }}"
      vars:
        packages:
          - php7.2-bz2
          - php7.2-mysql
          - php7.2-curl
          - php7.2-gd
          - php-imagick
          - php7.2-intl
          - php7.2-mbstring
          - php7.2-xml
          - php7.2-zip
          - owncloud-files
      become: yes

    - name: Enable pdo_mysql
      shell: phpenmod pdo_mysql
      become: yes

    - name: Configure Apache
      replace:
        path: /etc/apache2/sites-enabled/000-default.conf
        regexp: 'DocumentRoot\s\/var\/www\/html'
        replace: 'DocumentRoot /var/www/owncloud'
      become: yes

    - name: ufw settings
      shell: ufw allow 'Apache Full' && ufw delete allow 'Apache'
      become: yes

    - name: Restart Apache2
      service:
        name: apache2
        state: restarted
      become: yes